language: scala

before_script:
  - sudo service cassandra start
  - sudo chmod +x /usr/local/bin/sbt

script:
  - sbt -J-Xmx4G clean test doc

scala:
  - 2.12.2

jdk:
  - oraclejdk8

sudo: required

services:
  - mongodb

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - oracle-java8-installer

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e9d59e247d947e8f6410
    on_success: change
    on_failure: always
    on_start: never
