package longevity.integration.master

import longevity.IntegrationTest
import longevity.MasterIntegrationTest

@IntegrationTest
@MasterIntegrationTest
class InMemMasterSpec extends boundedContext.InMemRepoPoolSpec
