package longevity.integration.master

import longevity.IntegrationTest
import longevity.MasterIntegrationTest

@IntegrationTest
@MasterIntegrationTest
class MongoMasterSpec extends longevityContext.testContext.RepoPoolSpec
