package emblem

import org.scalatest._
import org.scalatest.OptionValues._

/** emblem specifications */
class EmblemSpec extends FlatSpec with GivenWhenThen with Matchers {

  case class Point(x: Double, y: Double) extends HasEmblem

  object PointEmblem extends Emblem[Point](
    "emblem.EmblemSpec",
    "Point",
    Seq(
      new EmblemProp[Point, Double]("x", _.x, (p, x) => p.copy(x = x)),
      new EmblemProp[Point, Double]("y", _.y, (p, y) => p.copy(y = y))
    ),
    Point(0, 0)
  ) {

    // TODO: these should be generated by def macro
    lazy val x = apply[Double]("x")
    lazy val y = apply[Double]("y")
  }

  behavior of "an emblem"

  it should "retain name information" in {
    PointEmblem.namePrefix should equal ("emblem.EmblemSpec")
    PointEmblem.name should equal ("Point")
    PointEmblem.fullname should equal ("emblem.EmblemSpec.Point")
  }

  it should "retain type information" in {
    PointEmblem.typeKey should equal (typeKey[Point])
  }

  it should "dump helpful debug info" in {
    PointEmblem.debugInfo should equal (
      """|emblem.EmblemSpec.Point {
         |  x: Double
         |  y: Double
         |}""".stripMargin)
  }

}
